stages:
- test

language: c
os: linux
dist: bionic

cache:
  npm: true

fast_finish: true

jobs:
  include:
  - stage: test
    env:
    - JOBNAME="Linux/x86-64 Correctness Tests"
    before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tools/apt-get-install-deps.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tools/brew-install-deps.sh; fi
    - tools/install-shadow-node.sh
    - yarn global add n
    - export N_PREFIX=$HOME/.node
    - export PATH=$(yarn global bin):$PATH
    install:
    - n 10
    - yarn
    script:
    - npm run lint
    - npm run test-local

  - stage: test
    env:
    - JOBNAME="Linux/x86-64 Correctness Build"
    script:
    - sudo tools/build-yodart.sh
